// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: article/v1/article_message.proto

package articlev1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PostStatus int32

const (
	PostStatus_Draft   PostStatus = 0
	PostStatus_Publish PostStatus = 1
	PostStatus_Trash   PostStatus = 2
)

// Enum value maps for PostStatus.
var (
	PostStatus_name = map[int32]string{
		0: "Draft",
		1: "Publish",
		2: "Trash",
	}
	PostStatus_value = map[string]int32{
		"Draft":   0,
		"Publish": 1,
		"Trash":   2,
	}
)

func (x PostStatus) Enum() *PostStatus {
	p := new(PostStatus)
	*p = x
	return p
}

func (x PostStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (PostStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_article_v1_article_message_proto_enumTypes[0].Descriptor()
}

func (PostStatus) Type() protoreflect.EnumType {
	return &file_article_v1_article_message_proto_enumTypes[0]
}

func (x PostStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use PostStatus.Descriptor instead.
func (PostStatus) EnumDescriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{0}
}

type BadRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Errors        map[string]string      `protobuf:"bytes,4,rep,name=errors,proto3" json:"errors,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BadRequest) Reset() {
	*x = BadRequest{}
	mi := &file_article_v1_article_message_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BadRequest) ProtoMessage() {}

func (x *BadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BadRequest.ProtoReflect.Descriptor instead.
func (*BadRequest) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{0}
}

func (x *BadRequest) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *BadRequest) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *BadRequest) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *BadRequest) GetErrors() map[string]string {
	if x != nil {
		return x.Errors
	}
	return nil
}

type Unauthorized struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Unauthorized) Reset() {
	*x = Unauthorized{}
	mi := &file_article_v1_article_message_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Unauthorized) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Unauthorized) ProtoMessage() {}

func (x *Unauthorized) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Unauthorized.ProtoReflect.Descriptor instead.
func (*Unauthorized) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{1}
}

func (x *Unauthorized) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Unauthorized) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Unauthorized) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Forbidden struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Forbidden) Reset() {
	*x = Forbidden{}
	mi := &file_article_v1_article_message_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Forbidden) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Forbidden) ProtoMessage() {}

func (x *Forbidden) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Forbidden.ProtoReflect.Descriptor instead.
func (*Forbidden) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{2}
}

func (x *Forbidden) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Forbidden) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Forbidden) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type NotFound struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NotFound) Reset() {
	*x = NotFound{}
	mi := &file_article_v1_article_message_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NotFound) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NotFound) ProtoMessage() {}

func (x *NotFound) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NotFound.ProtoReflect.Descriptor instead.
func (*NotFound) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{3}
}

func (x *NotFound) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *NotFound) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *NotFound) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type Conflict struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Conflict) Reset() {
	*x = Conflict{}
	mi := &file_article_v1_article_message_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Conflict) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Conflict) ProtoMessage() {}

func (x *Conflict) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Conflict.ProtoReflect.Descriptor instead.
func (*Conflict) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{4}
}

func (x *Conflict) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *Conflict) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Conflict) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type UnprocessableEntity struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UnprocessableEntity) Reset() {
	*x = UnprocessableEntity{}
	mi := &file_article_v1_article_message_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UnprocessableEntity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UnprocessableEntity) ProtoMessage() {}

func (x *UnprocessableEntity) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UnprocessableEntity.ProtoReflect.Descriptor instead.
func (*UnprocessableEntity) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{5}
}

func (x *UnprocessableEntity) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *UnprocessableEntity) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *UnprocessableEntity) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type InternalServerError struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalServerError) Reset() {
	*x = InternalServerError{}
	mi := &file_article_v1_article_message_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalServerError) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalServerError) ProtoMessage() {}

func (x *InternalServerError) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalServerError.ProtoReflect.Descriptor instead.
func (*InternalServerError) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{6}
}

func (x *InternalServerError) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InternalServerError) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InternalServerError) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type CommonResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CommonResponse) Reset() {
	*x = CommonResponse{}
	mi := &file_article_v1_article_message_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonResponse) ProtoMessage() {}

func (x *CommonResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonResponse.ProtoReflect.Descriptor instead.
func (*CommonResponse) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{7}
}

func (x *CommonResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *CommonResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *CommonResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type ParamID struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ParamID) Reset() {
	*x = ParamID{}
	mi := &file_article_v1_article_message_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ParamID) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ParamID) ProtoMessage() {}

func (x *ParamID) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ParamID.ProtoReflect.Descriptor instead.
func (*ParamID) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{8}
}

func (x *ParamID) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type HealthCheckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Message       string                 `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthCheckResponse) Reset() {
	*x = HealthCheckResponse{}
	mi := &file_article_v1_article_message_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthCheckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthCheckResponse) ProtoMessage() {}

func (x *HealthCheckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthCheckResponse.ProtoReflect.Descriptor instead.
func (*HealthCheckResponse) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{9}
}

func (x *HealthCheckResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// Post proto message
type GetPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	ItemPerPage   int32                  `protobuf:"varint,3,opt,name=item_per_page,json=itemPerPage,proto3" json:"item_per_page,omitempty"`
	Status        PostStatus             `protobuf:"varint,4,opt,name=status,proto3,enum=article.v1.PostStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsRequest) Reset() {
	*x = GetPostsRequest{}
	mi := &file_article_v1_article_message_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsRequest) ProtoMessage() {}

func (x *GetPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsRequest.ProtoReflect.Descriptor instead.
func (*GetPostsRequest) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{10}
}

func (x *GetPostsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *GetPostsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *GetPostsRequest) GetItemPerPage() int32 {
	if x != nil {
		return x.ItemPerPage
	}
	return 0
}

func (x *GetPostsRequest) GetStatus() PostStatus {
	if x != nil {
		return x.Status
	}
	return PostStatus_Draft
}

type GetPostsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Code          uint32                 `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                 `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                 `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GetPostsResponse_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsResponse) Reset() {
	*x = GetPostsResponse{}
	mi := &file_article_v1_article_message_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsResponse) ProtoMessage() {}

func (x *GetPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsResponse.ProtoReflect.Descriptor instead.
func (*GetPostsResponse) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{11}
}

func (x *GetPostsResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetPostsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetPostsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPostsResponse) GetData() *GetPostsResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type GetPostByIDResponse struct {
	state         protoimpl.MessageState    `protogen:"open.v1"`
	Code          uint32                    `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                    `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                    `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data          *GetPostByIDResponse_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostByIDResponse) Reset() {
	*x = GetPostByIDResponse{}
	mi := &file_article_v1_article_message_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostByIDResponse) ProtoMessage() {}

func (x *GetPostByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostByIDResponse.ProtoReflect.Descriptor instead.
func (*GetPostByIDResponse) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{12}
}

func (x *GetPostByIDResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *GetPostByIDResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *GetPostByIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *GetPostByIDResponse) GetData() *GetPostByIDResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

// Internal Post message
type InternalGetPostsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Search        string                 `protobuf:"bytes,1,opt,name=search,proto3" json:"search,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	ItemPerPage   int32                  `protobuf:"varint,3,opt,name=item_per_page,json=itemPerPage,proto3" json:"item_per_page,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalGetPostsRequest) Reset() {
	*x = InternalGetPostsRequest{}
	mi := &file_article_v1_article_message_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalGetPostsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalGetPostsRequest) ProtoMessage() {}

func (x *InternalGetPostsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalGetPostsRequest.ProtoReflect.Descriptor instead.
func (*InternalGetPostsRequest) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{13}
}

func (x *InternalGetPostsRequest) GetSearch() string {
	if x != nil {
		return x.Search
	}
	return ""
}

func (x *InternalGetPostsRequest) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *InternalGetPostsRequest) GetItemPerPage() int32 {
	if x != nil {
		return x.ItemPerPage
	}
	return 0
}

type InternalGetPostsResponse struct {
	state         protoimpl.MessageState         `protogen:"open.v1"`
	Code          uint32                         `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                         `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                         `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data          *InternalGetPostsResponse_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalGetPostsResponse) Reset() {
	*x = InternalGetPostsResponse{}
	mi := &file_article_v1_article_message_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalGetPostsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalGetPostsResponse) ProtoMessage() {}

func (x *InternalGetPostsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalGetPostsResponse.ProtoReflect.Descriptor instead.
func (*InternalGetPostsResponse) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{14}
}

func (x *InternalGetPostsResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InternalGetPostsResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InternalGetPostsResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InternalGetPostsResponse) GetData() *InternalGetPostsResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type InternalCreatePostRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	CreatedDate   string                 `protobuf:"bytes,4,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	UpdatedDate   string                 `protobuf:"bytes,5,opt,name=updated_date,json=updatedDate,proto3" json:"updated_date,omitempty"`
	Status        PostStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=article.v1.PostStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalCreatePostRequest) Reset() {
	*x = InternalCreatePostRequest{}
	mi := &file_article_v1_article_message_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalCreatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalCreatePostRequest) ProtoMessage() {}

func (x *InternalCreatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalCreatePostRequest.ProtoReflect.Descriptor instead.
func (*InternalCreatePostRequest) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{15}
}

func (x *InternalCreatePostRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InternalCreatePostRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *InternalCreatePostRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *InternalCreatePostRequest) GetCreatedDate() string {
	if x != nil {
		return x.CreatedDate
	}
	return ""
}

func (x *InternalCreatePostRequest) GetUpdatedDate() string {
	if x != nil {
		return x.UpdatedDate
	}
	return ""
}

func (x *InternalCreatePostRequest) GetStatus() PostStatus {
	if x != nil {
		return x.Status
	}
	return PostStatus_Draft
}

type InternalGetPostByIDResponse struct {
	state         protoimpl.MessageState            `protogen:"open.v1"`
	Code          uint32                            `protobuf:"varint,1,opt,name=code,proto3" json:"code,omitempty"`
	Status        string                            `protobuf:"bytes,2,opt,name=status,proto3" json:"status,omitempty"`
	Message       string                            `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
	Data          *InternalGetPostByIDResponse_Data `protobuf:"bytes,4,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalGetPostByIDResponse) Reset() {
	*x = InternalGetPostByIDResponse{}
	mi := &file_article_v1_article_message_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalGetPostByIDResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalGetPostByIDResponse) ProtoMessage() {}

func (x *InternalGetPostByIDResponse) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalGetPostByIDResponse.ProtoReflect.Descriptor instead.
func (*InternalGetPostByIDResponse) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{16}
}

func (x *InternalGetPostByIDResponse) GetCode() uint32 {
	if x != nil {
		return x.Code
	}
	return 0
}

func (x *InternalGetPostByIDResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *InternalGetPostByIDResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *InternalGetPostByIDResponse) GetData() *InternalGetPostByIDResponse_Data {
	if x != nil {
		return x.Data
	}
	return nil
}

type InternalUpdatePostRequest struct {
	state         protoimpl.MessageState                 `protogen:"open.v1"`
	Id            string                                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Body          *InternalUpdatePostRequest_BodyRequest `protobuf:"bytes,2,opt,name=body,proto3" json:"body,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalUpdatePostRequest) Reset() {
	*x = InternalUpdatePostRequest{}
	mi := &file_article_v1_article_message_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalUpdatePostRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalUpdatePostRequest) ProtoMessage() {}

func (x *InternalUpdatePostRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalUpdatePostRequest.ProtoReflect.Descriptor instead.
func (*InternalUpdatePostRequest) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{17}
}

func (x *InternalUpdatePostRequest) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InternalUpdatePostRequest) GetBody() *InternalUpdatePostRequest_BodyRequest {
	if x != nil {
		return x.Body
	}
	return nil
}

type GetPostsResponse_PostData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	CreatedDate   string                 `protobuf:"bytes,5,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	UpdatedDate   string                 `protobuf:"bytes,6,opt,name=updated_date,json=updatedDate,proto3" json:"updated_date,omitempty"`
	Status        PostStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=article.v1.PostStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsResponse_PostData) Reset() {
	*x = GetPostsResponse_PostData{}
	mi := &file_article_v1_article_message_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsResponse_PostData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsResponse_PostData) ProtoMessage() {}

func (x *GetPostsResponse_PostData) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsResponse_PostData.ProtoReflect.Descriptor instead.
func (*GetPostsResponse_PostData) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{11, 0}
}

func (x *GetPostsResponse_PostData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPostsResponse_PostData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetPostsResponse_PostData) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetPostsResponse_PostData) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetPostsResponse_PostData) GetCreatedDate() string {
	if x != nil {
		return x.CreatedDate
	}
	return ""
}

func (x *GetPostsResponse_PostData) GetUpdatedDate() string {
	if x != nil {
		return x.UpdatedDate
	}
	return ""
}

func (x *GetPostsResponse_PostData) GetStatus() PostStatus {
	if x != nil {
		return x.Status
	}
	return PostStatus_Draft
}

type GetPostsResponse_Data struct {
	state         protoimpl.MessageState       `protogen:"open.v1"`
	Items         []*GetPostsResponse_PostData `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         uint64                       `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostsResponse_Data) Reset() {
	*x = GetPostsResponse_Data{}
	mi := &file_article_v1_article_message_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostsResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostsResponse_Data) ProtoMessage() {}

func (x *GetPostsResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostsResponse_Data.ProtoReflect.Descriptor instead.
func (*GetPostsResponse_Data) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{11, 1}
}

func (x *GetPostsResponse_Data) GetItems() []*GetPostsResponse_PostData {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *GetPostsResponse_Data) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type GetPostByIDResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	CreatedDate   string                 `protobuf:"bytes,5,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	UpdatedDate   string                 `protobuf:"bytes,6,opt,name=updated_date,json=updatedDate,proto3" json:"updated_date,omitempty"`
	Status        PostStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=article.v1.PostStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetPostByIDResponse_Data) Reset() {
	*x = GetPostByIDResponse_Data{}
	mi := &file_article_v1_article_message_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetPostByIDResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetPostByIDResponse_Data) ProtoMessage() {}

func (x *GetPostByIDResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetPostByIDResponse_Data.ProtoReflect.Descriptor instead.
func (*GetPostByIDResponse_Data) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{12, 0}
}

func (x *GetPostByIDResponse_Data) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *GetPostByIDResponse_Data) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *GetPostByIDResponse_Data) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *GetPostByIDResponse_Data) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *GetPostByIDResponse_Data) GetCreatedDate() string {
	if x != nil {
		return x.CreatedDate
	}
	return ""
}

func (x *GetPostByIDResponse_Data) GetUpdatedDate() string {
	if x != nil {
		return x.UpdatedDate
	}
	return ""
}

func (x *GetPostByIDResponse_Data) GetStatus() PostStatus {
	if x != nil {
		return x.Status
	}
	return PostStatus_Draft
}

type InternalGetPostsResponse_PostData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	CreatedDate   string                 `protobuf:"bytes,5,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	UpdatedDate   string                 `protobuf:"bytes,6,opt,name=updated_date,json=updatedDate,proto3" json:"updated_date,omitempty"`
	Status        PostStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=article.v1.PostStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalGetPostsResponse_PostData) Reset() {
	*x = InternalGetPostsResponse_PostData{}
	mi := &file_article_v1_article_message_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalGetPostsResponse_PostData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalGetPostsResponse_PostData) ProtoMessage() {}

func (x *InternalGetPostsResponse_PostData) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalGetPostsResponse_PostData.ProtoReflect.Descriptor instead.
func (*InternalGetPostsResponse_PostData) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{14, 0}
}

func (x *InternalGetPostsResponse_PostData) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InternalGetPostsResponse_PostData) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InternalGetPostsResponse_PostData) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *InternalGetPostsResponse_PostData) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *InternalGetPostsResponse_PostData) GetCreatedDate() string {
	if x != nil {
		return x.CreatedDate
	}
	return ""
}

func (x *InternalGetPostsResponse_PostData) GetUpdatedDate() string {
	if x != nil {
		return x.UpdatedDate
	}
	return ""
}

func (x *InternalGetPostsResponse_PostData) GetStatus() PostStatus {
	if x != nil {
		return x.Status
	}
	return PostStatus_Draft
}

type InternalGetPostsResponse_Data struct {
	state         protoimpl.MessageState               `protogen:"open.v1"`
	Items         []*InternalGetPostsResponse_PostData `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	Total         uint64                               `protobuf:"varint,2,opt,name=total,proto3" json:"total,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalGetPostsResponse_Data) Reset() {
	*x = InternalGetPostsResponse_Data{}
	mi := &file_article_v1_article_message_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalGetPostsResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalGetPostsResponse_Data) ProtoMessage() {}

func (x *InternalGetPostsResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalGetPostsResponse_Data.ProtoReflect.Descriptor instead.
func (*InternalGetPostsResponse_Data) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{14, 1}
}

func (x *InternalGetPostsResponse_Data) GetItems() []*InternalGetPostsResponse_PostData {
	if x != nil {
		return x.Items
	}
	return nil
}

func (x *InternalGetPostsResponse_Data) GetTotal() uint64 {
	if x != nil {
		return x.Total
	}
	return 0
}

type InternalGetPostByIDResponse_Data struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title         string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,3,opt,name=content,proto3" json:"content,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	CreatedDate   string                 `protobuf:"bytes,5,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	UpdatedDate   string                 `protobuf:"bytes,6,opt,name=updated_date,json=updatedDate,proto3" json:"updated_date,omitempty"`
	Status        PostStatus             `protobuf:"varint,7,opt,name=status,proto3,enum=article.v1.PostStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalGetPostByIDResponse_Data) Reset() {
	*x = InternalGetPostByIDResponse_Data{}
	mi := &file_article_v1_article_message_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalGetPostByIDResponse_Data) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalGetPostByIDResponse_Data) ProtoMessage() {}

func (x *InternalGetPostByIDResponse_Data) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalGetPostByIDResponse_Data.ProtoReflect.Descriptor instead.
func (*InternalGetPostByIDResponse_Data) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{16, 0}
}

func (x *InternalGetPostByIDResponse_Data) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *InternalGetPostByIDResponse_Data) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InternalGetPostByIDResponse_Data) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *InternalGetPostByIDResponse_Data) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *InternalGetPostByIDResponse_Data) GetCreatedDate() string {
	if x != nil {
		return x.CreatedDate
	}
	return ""
}

func (x *InternalGetPostByIDResponse_Data) GetUpdatedDate() string {
	if x != nil {
		return x.UpdatedDate
	}
	return ""
}

func (x *InternalGetPostByIDResponse_Data) GetStatus() PostStatus {
	if x != nil {
		return x.Status
	}
	return PostStatus_Draft
}

type InternalUpdatePostRequest_BodyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Content       string                 `protobuf:"bytes,2,opt,name=content,proto3" json:"content,omitempty"`
	Category      string                 `protobuf:"bytes,3,opt,name=category,proto3" json:"category,omitempty"`
	CreatedDate   string                 `protobuf:"bytes,4,opt,name=created_date,json=createdDate,proto3" json:"created_date,omitempty"`
	UpdatedDate   string                 `protobuf:"bytes,5,opt,name=updated_date,json=updatedDate,proto3" json:"updated_date,omitempty"`
	Status        PostStatus             `protobuf:"varint,6,opt,name=status,proto3,enum=article.v1.PostStatus" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InternalUpdatePostRequest_BodyRequest) Reset() {
	*x = InternalUpdatePostRequest_BodyRequest{}
	mi := &file_article_v1_article_message_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InternalUpdatePostRequest_BodyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InternalUpdatePostRequest_BodyRequest) ProtoMessage() {}

func (x *InternalUpdatePostRequest_BodyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_article_v1_article_message_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InternalUpdatePostRequest_BodyRequest.ProtoReflect.Descriptor instead.
func (*InternalUpdatePostRequest_BodyRequest) Descriptor() ([]byte, []int) {
	return file_article_v1_article_message_proto_rawDescGZIP(), []int{17, 0}
}

func (x *InternalUpdatePostRequest_BodyRequest) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *InternalUpdatePostRequest_BodyRequest) GetContent() string {
	if x != nil {
		return x.Content
	}
	return ""
}

func (x *InternalUpdatePostRequest_BodyRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

func (x *InternalUpdatePostRequest_BodyRequest) GetCreatedDate() string {
	if x != nil {
		return x.CreatedDate
	}
	return ""
}

func (x *InternalUpdatePostRequest_BodyRequest) GetUpdatedDate() string {
	if x != nil {
		return x.UpdatedDate
	}
	return ""
}

func (x *InternalUpdatePostRequest_BodyRequest) GetStatus() PostStatus {
	if x != nil {
		return x.Status
	}
	return PostStatus_Draft
}

var File_article_v1_article_message_proto protoreflect.FileDescriptor

const file_article_v1_article_message_proto_rawDesc = "" +
	"\n" +
	" article/v1/article_message.proto\x12\n" +
	"article.v1\x1a.protoc-gen-openapiv2/options/annotations.proto\"\xa6\x02\n" +
	"\n" +
	"BadRequest\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"400\"R\x04code\x12*\n" +
	"\x06status\x18\x02 \x01(\tB\x12\x92A\x0fJ\r\"BAD REQUEST\"R\x06status\x12,\n" +
	"\amessage\x18\x03 \x01(\tB\x12\x92A\x0fJ\r\"Bad Request\"R\amessage\x12c\n" +
	"\x06errors\x18\x04 \x03(\v2\".article.v1.BadRequest.ErrorsEntryB'\x92A$J\"{\"field\": \"the field is required\"}R\x06errors\x1a9\n" +
	"\vErrorsEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12\x14\n" +
	"\x05value\x18\x02 \x01(\tR\x05value:\x028\x01\"\x8a\x01\n" +
	"\fUnauthorized\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"401\"R\x04code\x12+\n" +
	"\x06status\x18\x02 \x01(\tB\x13\x92A\x10J\x0e\"UNAUTHORIZED\"R\x06status\x12-\n" +
	"\amessage\x18\x03 \x01(\tB\x13\x92A\x10J\x0e\"Unauthorized\"R\amessage\"\x99\x01\n" +
	"\tForbidden\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"403\"R\x04code\x12(\n" +
	"\x06status\x18\x02 \x01(\tB\x10\x92A\rJ\v\"FORBIDDEN\"R\x06status\x12B\n" +
	"\amessage\x18\x03 \x01(\tB(\x92A%J#\"You does not have correct access.\"R\amessage\"\x86\x01\n" +
	"\bNotFound\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"404\"R\x04code\x12(\n" +
	"\x06status\x18\x02 \x01(\tB\x10\x92A\rJ\v\"NOT FOUND\"R\x06status\x120\n" +
	"\amessage\x18\x03 \x01(\tB\x16\x92A\x13J\x11\"Item not found.\"R\amessage\"\x8a\x01\n" +
	"\bConflict\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"419\"R\x04code\x12'\n" +
	"\x06status\x18\x02 \x01(\tB\x0f\x92A\fJ\n" +
	"\"CONFLICT\"R\x06status\x125\n" +
	"\amessage\x18\x03 \x01(\tB\x1b\x92A\x18J\x16\"Item already exists.\"R\amessage\"\xa1\x01\n" +
	"\x13UnprocessableEntity\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"422\"R\x04code\x123\n" +
	"\x06status\x18\x02 \x01(\tB\x1b\x92A\x18J\x16\"UNPROCESSABLE ENTITY\"R\x06status\x125\n" +
	"\amessage\x18\x03 \x01(\tB\x1b\x92A\x18J\x16\"Unprocessable entity\"R\amessage\"\xa3\x01\n" +
	"\x13InternalServerError\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"500\"R\x04code\x124\n" +
	"\x06status\x18\x02 \x01(\tB\x1c\x92A\x19J\x17\"INTERNAL SERVER ERROR\"R\x06status\x126\n" +
	"\amessage\x18\x03 \x01(\tB\x1c\x92A\x19J\x17\"Internal Server Error\"R\amessage\"\x91\x01\n" +
	"\x0eCommonResponse\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"200\"R\x04code\x12!\n" +
	"\x06status\x18\x02 \x01(\tB\t\x92A\x06J\x04\"OK\"R\x06status\x12<\n" +
	"\amessage\x18\x03 \x01(\tB\"\x92A\x1fJ\x1d\"Message of common response.\"R\amessage\"\x19\n" +
	"\aParamID\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\"G\n" +
	"\x13HealthCheckResponse\x120\n" +
	"\amessage\x18\x01 \x01(\tB\x16\x92A\x13J\x11\"Service Running\"R\amessage\"\xb1\x03\n" +
	"\x0fGetPostsRequest\x126\n" +
	"\x06search\x18\x01 \x01(\tB\x1e\x92A\x1b2\x19Search Posts By post nameR\x06search\x12{\n" +
	"\x04page\x18\x02 \x01(\x05Bg\x92Ad2\\Page number to get data, make value to -1 if you want ignore the pagination to get all rows.:\x011J\x011R\x04page\x12n\n" +
	"\ritem_per_page\x18\x03 \x01(\x05BJ\x92AG2=Limit data per page, leave it empty if the request page is -1:\x0210J\x0210R\vitemPerPage\x12.\n" +
	"\x06status\x18\x04 \x01(\x0e2\x16.article.v1.PostStatusR\x06status:I\x92AF\n" +
	"D*\x15Query Parameter Posts2+Query Parameter Schema in Get Posts Request\"\x93\x06\n" +
	"\x10GetPostsResponse\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"200\"R\x04code\x12!\n" +
	"\x06status\x18\x02 \x01(\tB\t\x92A\x06J\x04\"OK\"R\x06status\x12;\n" +
	"\amessage\x18\x03 \x01(\tB!\x92A\x1eJ\x1c\"Get List of posts success.\"R\amessage\x125\n" +
	"\x04data\x18\x04 \x01(\v2!.article.v1.GetPostsResponse.DataR\x04data\x1a\xd5\x03\n" +
	"\bPostData\x12;\n" +
	"\x02id\x18\x01 \x01(\tB+\x92A(J&\"b4f76920-ad2b-464a-a272-7af1db5288d3\"R\x02id\x12*\n" +
	"\x05title\x18\x02 \x01(\tB\x14\x92A\x11J\x0f\"Title of post\"R\x05title\x12A\n" +
	"\acontent\x18\x03 \x01(\tB'\x92A$J\"\"Content can be free text or html\"R\acontent\x12C\n" +
	"\bcategory\x18\x04 \x01(\tB'\x92A$J\"\"Content can be free text or html\"R\bcategory\x127\n" +
	"\fcreated_date\x18\x05 \x01(\tB\x14\x92A\x11J\x0f\"01 March 2024\"R\vcreatedDate\x127\n" +
	"\fupdated_date\x18\x06 \x01(\tB\x14\x92A\x11J\x0f\"01 March 2024\"R\vupdatedDate\x12f\n" +
	"\x06status\x18\a \x01(\x0e2\x16.article.v1.PostStatusB6\x92A3J1\"For the example can be: Draft, Publish or Trash\"R\x06status\x1ap\n" +
	"\x04Data\x12;\n" +
	"\x05items\x18\x01 \x03(\v2%.article.v1.GetPostsResponse.PostDataR\x05items\x12+\n" +
	"\x05total\x18\x02 \x01(\x04B\x15\x92A\x122\n" +
	"Total dataJ\x04\"10\"R\x05total\"\x9d\x05\n" +
	"\x13GetPostByIDResponse\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"200\"R\x04code\x12!\n" +
	"\x06status\x18\x02 \x01(\tB\t\x92A\x06J\x04\"OK\"R\x06status\x125\n" +
	"\amessage\x18\x03 \x01(\tB\x1b\x92A\x18J\x16\"Get article success.\"R\amessage\x128\n" +
	"\x04data\x18\x04 \x01(\v2$.article.v1.GetPostByIDResponse.DataR\x04data\x1a\xd1\x03\n" +
	"\x04Data\x12;\n" +
	"\x02id\x18\x01 \x01(\tB+\x92A(J&\"b4f76920-ad2b-464a-a272-7af1db5288d3\"R\x02id\x12*\n" +
	"\x05title\x18\x02 \x01(\tB\x14\x92A\x11J\x0f\"Title of post\"R\x05title\x12A\n" +
	"\acontent\x18\x03 \x01(\tB'\x92A$J\"\"Content can be free text or html\"R\acontent\x12C\n" +
	"\bcategory\x18\x04 \x01(\tB'\x92A$J\"\"Content can be free text or html\"R\bcategory\x127\n" +
	"\fcreated_date\x18\x05 \x01(\tB\x14\x92A\x11J\x0f\"01 March 2024\"R\vcreatedDate\x127\n" +
	"\fupdated_date\x18\x06 \x01(\tB\x14\x92A\x11J\x0f\"01 March 2024\"R\vupdatedDate\x12f\n" +
	"\x06status\x18\a \x01(\x0e2\x16.article.v1.PostStatusB6\x92A3J1\"For the example can be: Draft, Publish or Trash\"R\x06status\"\x93\x03\n" +
	"\x17InternalGetPostsRequest\x129\n" +
	"\x06search\x18\x01 \x01(\tB!\x92A\x1e2\x1cSearch Posts By article nameR\x06search\x12{\n" +
	"\x04page\x18\x02 \x01(\x05Bg\x92Ad2\\Page number to get data, make value to -1 if you want ignore the pagination to get all rows.:\x011J\x011R\x04page\x12n\n" +
	"\ritem_per_page\x18\x03 \x01(\x05BJ\x92AG2=Limit data per page, leave it empty if the request page is -1:\x0210J\x0210R\vitemPerPage:P\x92AM\n" +
	"K*\x15Query Parameter Posts2+Query Parameter Schema in Get Posts Request\xd2\x01\x04page\"\xae\x06\n" +
	"\x18InternalGetPostsResponse\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"200\"R\x04code\x12!\n" +
	"\x06status\x18\x02 \x01(\tB\t\x92A\x06J\x04\"OK\"R\x06status\x12>\n" +
	"\amessage\x18\x03 \x01(\tB$\x92A!J\x1f\"Get List of articles success.\"R\amessage\x12=\n" +
	"\x04data\x18\x04 \x01(\v2).article.v1.InternalGetPostsResponse.DataR\x04data\x1a\xd5\x03\n" +
	"\bPostData\x12;\n" +
	"\x02id\x18\x01 \x01(\tB+\x92A(J&\"b4f76920-ad2b-464a-a272-7af1db5288d3\"R\x02id\x12*\n" +
	"\x05title\x18\x02 \x01(\tB\x14\x92A\x11J\x0f\"Title of post\"R\x05title\x12A\n" +
	"\acontent\x18\x03 \x01(\tB'\x92A$J\"\"Content can be free text or html\"R\acontent\x12C\n" +
	"\bcategory\x18\x04 \x01(\tB'\x92A$J\"\"Content can be free text or html\"R\bcategory\x127\n" +
	"\fcreated_date\x18\x05 \x01(\tB\x14\x92A\x11J\x0f\"01 March 2024\"R\vcreatedDate\x127\n" +
	"\fupdated_date\x18\x06 \x01(\tB\x14\x92A\x11J\x0f\"01 March 2024\"R\vupdatedDate\x12f\n" +
	"\x06status\x18\a \x01(\x0e2\x16.article.v1.PostStatusB6\x92A3J1\"For the example can be: Draft, Publish or Trash\"R\x06status\x1ax\n" +
	"\x04Data\x12C\n" +
	"\x05items\x18\x01 \x03(\v2-.article.v1.InternalGetPostsResponse.PostDataR\x05items\x12+\n" +
	"\x05total\x18\x02 \x01(\x04B\x15\x92A\x122\n" +
	"Total dataJ\x04\"10\"R\x05total\"\x80\x04\n" +
	"\x19InternalCreatePostRequest\x12*\n" +
	"\x05title\x18\x01 \x01(\tB\x14\x92A\x11J\x0f\"Title of post\"R\x05title\x12A\n" +
	"\acontent\x18\x02 \x01(\tB'\x92A$J\"\"Content can be free text or html\"R\acontent\x12C\n" +
	"\bcategory\x18\x03 \x01(\tB'\x92A$J\"\"Content can be free text or html\"R\bcategory\x127\n" +
	"\fcreated_date\x18\x04 \x01(\tB\x14\x92A\x11J\x0f\"01 March 2024\"R\vcreatedDate\x127\n" +
	"\fupdated_date\x18\x05 \x01(\tB\x14\x92A\x11J\x0f\"01 March 2024\"R\vupdatedDate\x12f\n" +
	"\x06status\x18\x06 \x01(\x0e2\x16.article.v1.PostStatusB6\x92A3J1\"For the example can be: Draft, Publish or Trash\"R\x06status:U\x92AR\n" +
	"P*\x13Create Post Request2\x13Create Post Request\xd2\x01\x05title\xd2\x01\acontent\xd2\x01\bcategory\xd2\x01\x06status\"\xb3\x05\n" +
	"\x1bInternalGetPostByIDResponse\x12\x1e\n" +
	"\x04code\x18\x01 \x01(\rB\n" +
	"\x92A\aJ\x05\"200\"R\x04code\x12!\n" +
	"\x06status\x18\x02 \x01(\tB\t\x92A\x06J\x04\"OK\"R\x06status\x12;\n" +
	"\amessage\x18\x03 \x01(\tB!\x92A\x1eJ\x1c\"Get article by id success.\"R\amessage\x12@\n" +
	"\x04data\x18\x04 \x01(\v2,.article.v1.InternalGetPostByIDResponse.DataR\x04data\x1a\xd1\x03\n" +
	"\x04Data\x12;\n" +
	"\x02id\x18\x01 \x01(\tB+\x92A(J&\"b4f76920-ad2b-464a-a272-7af1db5288d3\"R\x02id\x12*\n" +
	"\x05title\x18\x02 \x01(\tB\x14\x92A\x11J\x0f\"Title of post\"R\x05title\x12A\n" +
	"\acontent\x18\x03 \x01(\tB'\x92A$J\"\"Content can be free text or html\"R\acontent\x12C\n" +
	"\bcategory\x18\x04 \x01(\tB'\x92A$J\"\"Content can be free text or html\"R\bcategory\x127\n" +
	"\fcreated_date\x18\x05 \x01(\tB\x14\x92A\x11J\x0f\"01 March 2024\"R\vcreatedDate\x127\n" +
	"\fupdated_date\x18\x06 \x01(\tB\x14\x92A\x11J\x0f\"01 March 2024\"R\vupdatedDate\x12f\n" +
	"\x06status\x18\a \x01(\x0e2\x16.article.v1.PostStatusB6\x92A3J1\"For the example can be: Draft, Publish or Trash\"R\x06status\"\xcd\x04\n" +
	"\x19InternalUpdatePostRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12E\n" +
	"\x04body\x18\x02 \x01(\v21.article.v1.InternalUpdatePostRequest.BodyRequestR\x04body\x1a\x9b\x03\n" +
	"\vBodyRequest\x12*\n" +
	"\x05title\x18\x01 \x01(\tB\x14\x92A\x11J\x0f\"Title of post\"R\x05title\x12A\n" +
	"\acontent\x18\x02 \x01(\tB'\x92A$J\"\"Content can be free text or html\"R\acontent\x12C\n" +
	"\bcategory\x18\x03 \x01(\tB'\x92A$J\"\"Content can be free text or html\"R\bcategory\x127\n" +
	"\fcreated_date\x18\x04 \x01(\tB\x14\x92A\x11J\x0f\"01 March 2024\"R\vcreatedDate\x127\n" +
	"\fupdated_date\x18\x05 \x01(\tB\x14\x92A\x11J\x0f\"01 March 2024\"R\vupdatedDate\x12f\n" +
	"\x06status\x18\x06 \x01(\x0e2\x16.article.v1.PostStatusB6\x92A3J1\"For the example can be: Draft, Publish or Trash\"R\x06status:;\x92A8\n" +
	"6*\x13Update Post Request2\x13Update Post Request\xd2\x01\x02id\xd2\x01\x04body*/\n" +
	"\n" +
	"PostStatus\x12\t\n" +
	"\x05Draft\x10\x00\x12\v\n" +
	"\aPublish\x10\x01\x12\t\n" +
	"\x05Trash\x10\x02B@Z>github.com/Kkmikaze/article-service/proto/article/v1;articlev1b\x06proto3"

var (
	file_article_v1_article_message_proto_rawDescOnce sync.Once
	file_article_v1_article_message_proto_rawDescData []byte
)

func file_article_v1_article_message_proto_rawDescGZIP() []byte {
	file_article_v1_article_message_proto_rawDescOnce.Do(func() {
		file_article_v1_article_message_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_article_v1_article_message_proto_rawDesc), len(file_article_v1_article_message_proto_rawDesc)))
	})
	return file_article_v1_article_message_proto_rawDescData
}

var file_article_v1_article_message_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_article_v1_article_message_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_article_v1_article_message_proto_goTypes = []any{
	(PostStatus)(0),                               // 0: article.v1.PostStatus
	(*BadRequest)(nil),                            // 1: article.v1.BadRequest
	(*Unauthorized)(nil),                          // 2: article.v1.Unauthorized
	(*Forbidden)(nil),                             // 3: article.v1.Forbidden
	(*NotFound)(nil),                              // 4: article.v1.NotFound
	(*Conflict)(nil),                              // 5: article.v1.Conflict
	(*UnprocessableEntity)(nil),                   // 6: article.v1.UnprocessableEntity
	(*InternalServerError)(nil),                   // 7: article.v1.InternalServerError
	(*CommonResponse)(nil),                        // 8: article.v1.CommonResponse
	(*ParamID)(nil),                               // 9: article.v1.ParamID
	(*HealthCheckResponse)(nil),                   // 10: article.v1.HealthCheckResponse
	(*GetPostsRequest)(nil),                       // 11: article.v1.GetPostsRequest
	(*GetPostsResponse)(nil),                      // 12: article.v1.GetPostsResponse
	(*GetPostByIDResponse)(nil),                   // 13: article.v1.GetPostByIDResponse
	(*InternalGetPostsRequest)(nil),               // 14: article.v1.InternalGetPostsRequest
	(*InternalGetPostsResponse)(nil),              // 15: article.v1.InternalGetPostsResponse
	(*InternalCreatePostRequest)(nil),             // 16: article.v1.InternalCreatePostRequest
	(*InternalGetPostByIDResponse)(nil),           // 17: article.v1.InternalGetPostByIDResponse
	(*InternalUpdatePostRequest)(nil),             // 18: article.v1.InternalUpdatePostRequest
	nil,                                           // 19: article.v1.BadRequest.ErrorsEntry
	(*GetPostsResponse_PostData)(nil),             // 20: article.v1.GetPostsResponse.PostData
	(*GetPostsResponse_Data)(nil),                 // 21: article.v1.GetPostsResponse.Data
	(*GetPostByIDResponse_Data)(nil),              // 22: article.v1.GetPostByIDResponse.Data
	(*InternalGetPostsResponse_PostData)(nil),     // 23: article.v1.InternalGetPostsResponse.PostData
	(*InternalGetPostsResponse_Data)(nil),         // 24: article.v1.InternalGetPostsResponse.Data
	(*InternalGetPostByIDResponse_Data)(nil),      // 25: article.v1.InternalGetPostByIDResponse.Data
	(*InternalUpdatePostRequest_BodyRequest)(nil), // 26: article.v1.InternalUpdatePostRequest.BodyRequest
}
var file_article_v1_article_message_proto_depIdxs = []int32{
	19, // 0: article.v1.BadRequest.errors:type_name -> article.v1.BadRequest.ErrorsEntry
	0,  // 1: article.v1.GetPostsRequest.status:type_name -> article.v1.PostStatus
	21, // 2: article.v1.GetPostsResponse.data:type_name -> article.v1.GetPostsResponse.Data
	22, // 3: article.v1.GetPostByIDResponse.data:type_name -> article.v1.GetPostByIDResponse.Data
	24, // 4: article.v1.InternalGetPostsResponse.data:type_name -> article.v1.InternalGetPostsResponse.Data
	0,  // 5: article.v1.InternalCreatePostRequest.status:type_name -> article.v1.PostStatus
	25, // 6: article.v1.InternalGetPostByIDResponse.data:type_name -> article.v1.InternalGetPostByIDResponse.Data
	26, // 7: article.v1.InternalUpdatePostRequest.body:type_name -> article.v1.InternalUpdatePostRequest.BodyRequest
	0,  // 8: article.v1.GetPostsResponse.PostData.status:type_name -> article.v1.PostStatus
	20, // 9: article.v1.GetPostsResponse.Data.items:type_name -> article.v1.GetPostsResponse.PostData
	0,  // 10: article.v1.GetPostByIDResponse.Data.status:type_name -> article.v1.PostStatus
	0,  // 11: article.v1.InternalGetPostsResponse.PostData.status:type_name -> article.v1.PostStatus
	23, // 12: article.v1.InternalGetPostsResponse.Data.items:type_name -> article.v1.InternalGetPostsResponse.PostData
	0,  // 13: article.v1.InternalGetPostByIDResponse.Data.status:type_name -> article.v1.PostStatus
	0,  // 14: article.v1.InternalUpdatePostRequest.BodyRequest.status:type_name -> article.v1.PostStatus
	15, // [15:15] is the sub-list for method output_type
	15, // [15:15] is the sub-list for method input_type
	15, // [15:15] is the sub-list for extension type_name
	15, // [15:15] is the sub-list for extension extendee
	0,  // [0:15] is the sub-list for field type_name
}

func init() { file_article_v1_article_message_proto_init() }
func file_article_v1_article_message_proto_init() {
	if File_article_v1_article_message_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_article_v1_article_message_proto_rawDesc), len(file_article_v1_article_message_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_article_v1_article_message_proto_goTypes,
		DependencyIndexes: file_article_v1_article_message_proto_depIdxs,
		EnumInfos:         file_article_v1_article_message_proto_enumTypes,
		MessageInfos:      file_article_v1_article_message_proto_msgTypes,
	}.Build()
	File_article_v1_article_message_proto = out.File
	file_article_v1_article_message_proto_goTypes = nil
	file_article_v1_article_message_proto_depIdxs = nil
}
