// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v3.21.12
// source: article/v1/article_service.proto

package articlev1

import (
	_ "github.com/grpc-ecosystem/grpc-gateway/v2/protoc-gen-openapiv2/options"
	_ "google.golang.org/genproto/googleapis/api/annotations"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	reflect "reflect"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

var File_article_v1_article_service_proto protoreflect.FileDescriptor

const file_article_v1_article_service_proto_rawDesc = "" +
	"\n" +
	" article/v1/article_service.proto\x12\n" +
	"article.v1\x1a\x1cgoogle/api/annotations.proto\x1a\x1bgoogle/protobuf/empty.proto\x1a.protoc-gen-openapiv2/options/annotations.proto\x1a article/v1/article_message.proto2\xa8\x0f\n" +
	"\x0eArticleService\x12\xa5\x01\n" +
	"\fHealthzCheck\x12\x16.google.protobuf.Empty\x1a\x1f.article.v1.HealthCheckResponse\"\\\x92A2J0\n" +
	"\x03200\x12)\n" +
	"\x02OK\x12#\n" +
	"!\x1a\x1f.article.v1.HealthCheckResponse\x82\xd3\xe4\x93\x02!\x12\x1f/api/v1/article-service/healthz\x12\xeb\x01\n" +
	"\bGetPosts\x12\x1b.article.v1.GetPostsRequest\x1a\x1c.article.v1.GetPostsResponse\"\xa3\x01\x92A{\n" +
	"\x04Post\x12\tGet Posts\x1a9This API for get list of posts that associated with eventJ-\n" +
	"\x03200\x12&\n" +
	"\x02OK\x12 \n" +
	"\x1e\x1a\x1c.article.v1.GetPostsResponse\x82\xd3\xe4\x93\x02\x1f\x12\x1d/api/v1/article-service/posts\x12\xd9\x01\n" +
	"\vGetPostByID\x12\x13.article.v1.ParamID\x1a\x1f.article.v1.GetPostByIDResponse\"\x93\x01\x92Af\n" +
	"\x04Post\x12\bGet Post\x1a\"This API for get detail of articleJ0\n" +
	"\x03200\x12)\n" +
	"\x02OK\x12#\n" +
	"!\x1a\x1f.article.v1.GetPostByIDResponse\x82\xd3\xe4\x93\x02$\x12\"/api/v1/article-service/posts/{id}\x12\x84\x02\n" +
	"\x10InternalGetPosts\x12#.article.v1.InternalGetPostsRequest\x1a$.article.v1.InternalGetPostsResponse\"\xa4\x01\x92As\n" +
	"\x0fInternal - Post\x12\tGet Posts\x1a\x1eThis API for get list of postsJ5\n" +
	"\x03200\x12.\n" +
	"\x02OK\x12(\n" +
	"&\x1a$.article.v1.InternalGetPostsResponse\x82\xd3\xe4\x93\x02(\x12&/api/v1/article-service/internal/posts\x12\xf4\x01\n" +
	"\x12InternalCreatePost\x12%.article.v1.InternalCreatePostRequest\x1a\x1a.article.v1.CommonResponse\"\x9a\x01\x92Af\n" +
	"\x0fInternal - Post\x12\vCreate Post\x1a\x19This API for create post.J+\n" +
	"\x03200\x12$\n" +
	"\x02OK\x12\x1e\n" +
	"\x1c\x1a\x1a.article.v1.CommonResponse\x82\xd3\xe4\x93\x02+:\x01*\"&/api/v1/article-service/internal/posts\x12\x9d\x02\n" +
	"\x13InternalGetPostByID\x12\x13.article.v1.ParamID\x1a'.article.v1.InternalGetPostByIDResponse\"\xc7\x01\x92A\x90\x01\n" +
	"\x0fInternal - Post\x12\x1aGet Post Detail by Post ID\x1a'This API for get post detail by post idJ8\n" +
	"\x03200\x121\n" +
	"\x02OK\x12+\n" +
	")\x1a'.article.v1.InternalGetPostByIDResponse\x82\xd3\xe4\x93\x02-\x12+/api/v1/article-service/internal/posts/{id}\x12\xfc\x01\n" +
	"\x12InternalUpdatePost\x12%.article.v1.InternalUpdatePostRequest\x1a\x1a.article.v1.CommonResponse\"\xa2\x01\x92Af\n" +
	"\x0fInternal - Post\x12\vUpdate Post\x1a\x19This API for update post.J+\n" +
	"\x03200\x12$\n" +
	"\x02OK\x12\x1e\n" +
	"\x1c\x1a\x1a.article.v1.CommonResponse\x82\xd3\xe4\x93\x023:\x04body\x1a+/api/v1/article-service/internal/posts/{id}\x12\x86\x02\n" +
	"\x16InternalDeletePostByID\x12\x13.article.v1.ParamID\x1a\x1a.article.v1.CommonResponse\"\xba\x01\x92A\x83\x01\n" +
	"\x0fInternal - Post\x12\x1aGet Post Delete by Post ID\x1a'This API for get post delete by post idJ+\n" +
	"\x03200\x12$\n" +
	"\x02OK\x12\x1e\n" +
	"\x1c\x1a\x1a.article.v1.CommonResponse\x82\xd3\xe4\x93\x02-*+/api/v1/article-service/internal/posts/{id}B\xd9\x03\x92A\x95\x03\x12\x19\n" +
	"\x0fArticle Service2\x06v1.0.0R0\n" +
	"\x03400\x12)\n" +
	"\vBad Request\x12\x1a\n" +
	"\x18\x1a\x16.article.v1.BadRequestR3\n" +
	"\x03401\x12,\n" +
	"\fUnauthorized\x12\x1c\n" +
	"\x1a\x1a\x18.article.v1.UnauthorizedR-\n" +
	"\x03403\x12&\n" +
	"\tForbidden\x12\x19\n" +
	"\x17\x1a\x15.article.v1.ForbiddenR,\n" +
	"\x03404\x12%\n" +
	"\tNot Found\x12\x18\n" +
	"\x16\x1a\x14.article.v1.NotFoundR+\n" +
	"\x03419\x12$\n" +
	"\bConflict\x12\x18\n" +
	"\x16\x1a\x14.article.v1.ConflictRB\n" +
	"\x03422\x12;\n" +
	"\x14Unprocessable Entity\x12#\n" +
	"!\x1a\x1f.article.v1.UnprocessableEntityRC\n" +
	"\x03500\x12<\n" +
	"\x15Internal Server Error\x12#\n" +
	"!\x1a\x1f.article.v1.InternalServerErrorZ>github.com/Kkmikaze/article-service/proto/article/v1;articlev1b\x06proto3"

var file_article_v1_article_service_proto_goTypes = []any{
	(*emptypb.Empty)(nil),               // 0: google.protobuf.Empty
	(*GetPostsRequest)(nil),             // 1: article.v1.GetPostsRequest
	(*ParamID)(nil),                     // 2: article.v1.ParamID
	(*InternalGetPostsRequest)(nil),     // 3: article.v1.InternalGetPostsRequest
	(*InternalCreatePostRequest)(nil),   // 4: article.v1.InternalCreatePostRequest
	(*InternalUpdatePostRequest)(nil),   // 5: article.v1.InternalUpdatePostRequest
	(*HealthCheckResponse)(nil),         // 6: article.v1.HealthCheckResponse
	(*GetPostsResponse)(nil),            // 7: article.v1.GetPostsResponse
	(*GetPostByIDResponse)(nil),         // 8: article.v1.GetPostByIDResponse
	(*InternalGetPostsResponse)(nil),    // 9: article.v1.InternalGetPostsResponse
	(*CommonResponse)(nil),              // 10: article.v1.CommonResponse
	(*InternalGetPostByIDResponse)(nil), // 11: article.v1.InternalGetPostByIDResponse
}
var file_article_v1_article_service_proto_depIdxs = []int32{
	0,  // 0: article.v1.ArticleService.HealthzCheck:input_type -> google.protobuf.Empty
	1,  // 1: article.v1.ArticleService.GetPosts:input_type -> article.v1.GetPostsRequest
	2,  // 2: article.v1.ArticleService.GetPostByID:input_type -> article.v1.ParamID
	3,  // 3: article.v1.ArticleService.InternalGetPosts:input_type -> article.v1.InternalGetPostsRequest
	4,  // 4: article.v1.ArticleService.InternalCreatePost:input_type -> article.v1.InternalCreatePostRequest
	2,  // 5: article.v1.ArticleService.InternalGetPostByID:input_type -> article.v1.ParamID
	5,  // 6: article.v1.ArticleService.InternalUpdatePost:input_type -> article.v1.InternalUpdatePostRequest
	2,  // 7: article.v1.ArticleService.InternalDeletePostByID:input_type -> article.v1.ParamID
	6,  // 8: article.v1.ArticleService.HealthzCheck:output_type -> article.v1.HealthCheckResponse
	7,  // 9: article.v1.ArticleService.GetPosts:output_type -> article.v1.GetPostsResponse
	8,  // 10: article.v1.ArticleService.GetPostByID:output_type -> article.v1.GetPostByIDResponse
	9,  // 11: article.v1.ArticleService.InternalGetPosts:output_type -> article.v1.InternalGetPostsResponse
	10, // 12: article.v1.ArticleService.InternalCreatePost:output_type -> article.v1.CommonResponse
	11, // 13: article.v1.ArticleService.InternalGetPostByID:output_type -> article.v1.InternalGetPostByIDResponse
	10, // 14: article.v1.ArticleService.InternalUpdatePost:output_type -> article.v1.CommonResponse
	10, // 15: article.v1.ArticleService.InternalDeletePostByID:output_type -> article.v1.CommonResponse
	8,  // [8:16] is the sub-list for method output_type
	0,  // [0:8] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_article_v1_article_service_proto_init() }
func file_article_v1_article_service_proto_init() {
	if File_article_v1_article_service_proto != nil {
		return
	}
	file_article_v1_article_message_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_article_v1_article_service_proto_rawDesc), len(file_article_v1_article_service_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   0,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_article_v1_article_service_proto_goTypes,
		DependencyIndexes: file_article_v1_article_service_proto_depIdxs,
	}.Build()
	File_article_v1_article_service_proto = out.File
	file_article_v1_article_service_proto_goTypes = nil
	file_article_v1_article_service_proto_depIdxs = nil
}
